#!/bin/bash
LOCAL_RANK=${OMPI_COMM_WORLD_LOCAL_RANK:-${OMPI_COMM_WORLD_RANK:-0}}
echo "[gpu_bind] pid=$$  OMPI_COMM_WORLD_LOCAL_RANK=${OMPI_COMM_WORLD_LOCAL_RANK}  OMPI_COMM_WORLD_RANK=${OMPI_COMM_WORLD_RANK}  -> CUDA_VISIBLE_DEVICES=${LOCAL_RANK}" >&2
export CUDA_VISIBLE_DEVICES=$LOCAL_RANK
exec "$@"
